### ISSUE TITLE
question mark icon should show helpful information in multi-level indicator

### ISSUE THREAD

**Issue by Aaegamysta** [ahmedmohyh/OpenLap-IndicatorEditor#10]
Slide 73
![Image](https://github.com/ahmedmohyh/OpenLap-IndicatorEditor/assets/158301581/1ca72134-afc5-4ce5-9a0a-df67f2a0dee6)

**Comment by Mehdi-ghaffari** [comment]
Test : Mehdi Ghaffari (Visualization Library)
Test : Mehdi Ghaffari (Visualization Type)
